export const BookGenres = [
   { label: 'Fantasia', value: 'Fantasia' },
   { label: 'Ficção científica', value: 'Ficção científica' },
   { label: 'Distopia', value: 'Distopia' },
   { label: 'Ação', value: 'Ação' },
   { label: 'Aventura', value: 'Aventura' },
   { label: 'Ficção Policial', value: 'Ficção Policial' },
   { label: 'Horror', value: 'Horror' },
   { label: 'Thriller', value: 'Thriller' },
   { label: 'Suspense', value: 'Suspense' },
   { label: 'Ficção histórica', value: 'Ficção histórica' },
   { label: 'Romance', value: 'Romance' },
   { label: 'LGBTQ+', value: 'LGBTQ+' },
   { label: 'Ficção Contemporânea', value: 'Ficção Contemporânea' },
   { label: 'Graphic Novel', value: 'Graphic Novel' },
   { label: 'Conto', value: 'Conto' },
   { label: 'Infantil', value: 'Infantil' },
   { label: 'Autobiografia', value: 'Autobiografia' },
   { label: 'Biografia', value: 'Biografia' },
   { label: 'Gastronomia', value: 'Gastronomia' },
   { label: 'Arte', value: 'Arte' },
   { label: 'Fotografia', value: 'Fotografia' },
   { label: 'Autoajuda', value: 'Autoajuda' },
   { label: 'História', value: 'História' },
   { label: 'Viajem', value: 'Viajem' },
   { label: 'Crimes Reais', value: 'Crimes Reais' },
   { label: 'Humor', value: 'Humor' },
   { label: 'Ensaios', value: 'Ensaios' },
   { label: 'Guias & Como fazer', value: 'Guias & Como fazer' },
   { label: 'Religião', value: 'Religião' },
   { label: 'Espiritualidade', value: 'Espiritualidade' },
   { label: 'Ciências Sociais', value: 'Ciências Sociais' },
   { label: 'Tecnologia', value: 'Tecnologia' },
   { label: 'Ciência', value: 'Ciência' },
   { label: 'Infantil', value: ' Infantil' },
];
